# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03edb75fc0ab56b0fab422af25c2486566e6f11a2930f398a03f981134e4ec96472a46d6db46f7e5d51a2a18afea5e1964d3eaa51214033777bb649b054c63f

test:
  secret_key_base: 689d2978bbd7d12af937bc18c0f9fc10b6d59b65f6e5c733674a422a488989151367816e3464daed8e35f3dd8a3793d6203136a4460eae7271db1a87415befae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
